baseurl = "https://ocs-coes.netlify.app/"
title = "Observatorio de Cohesión Social"
theme = "hugo-universal-theme"
languageCode = "es-cl"
ignoreFiles = [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "G-5NZ26DZ60M"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]] # Inicio
    identifier="home"
    name = "Inicio"
    url  = "/"
    weight = 1

#[[menu.main]] # Menu Sobre el OCS
#    identifier="about"
#    name      = "Sobre el OCS"
#    url       = "/about/"
#    weight    = 2  
     
#[[menu.main]] # Menu Noticia
#    identifier="blog"
#    name      = "Noticias"
#    url       = "/blog/"
#    weight    = 2

[[menu.main]] # Menu Recursos
    name       = "Reportes"
    identifier = "section.publicaciones"
    url        = "/pubs/" 
    weight     = 3
 
[[menu.main]] # Menu Analisis
    identifier = "analisis"
    name = "Analisis"
    url  = ""
    weight = 4
    
[[menu.main]] # Submenu: shiny app - LAPOP
    identifier = "app.lapop" 
    parent     = "analisis"
    name = "LAPOP"
    url  = "/app/"
    weight = 1 
    
[[menu.main]] # Submenu: shiny app - LAPOP
    identifier = "app.LA" 
    parent     = "analisis"
    name = "América Latina"
    url  = "/cohesion-LA/"
    weight = 2

#[[menu.main]] # Submenu: documentacion shiny
#    identifier = "app.docu"
#    parent     = "analisis"
#    name = "Documentación"
#    url  = "/doc2/"
#    weight = 1
  
[[menu.main]] # Submenu: shiny app - LAPOP
    identifier = "app.chile" 
    parent     = "analisis"
    name = "Chile"
    url  = "/app-elsoc/"
    weight = 1      
    
[[menu.main]] # Menu enlaces
    identifier = "section.links"
    name = "Enlaces"
    url  = "/links/"
    weight = 5    

#[[menu.main]] # Menu enlaces
#    identifier = "contact"
#    name = "Contacto"
#    url  = "/contact/"
#    weight = 6  
    
# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/ocscoes/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/CentroCOES"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "https://twitter.com/CentroCOES"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:ocs@coes.cl"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "OCS"
    defaultKeywords = ["cohesion", "visualizador", "LAPOP"]
    mainSections = ["blog"]
    defaultDescription = "Sitio desarrollado por valentinaandrade por template devcows usando hugo"

    # Social media
    facebook_site = "coes2020" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "CentroCOES" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = false
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "ocs"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "f/xeqpkdpl"
    contact_form_ajax = false

    about_us = "<p>Observatorio de Cohesión Social, COES</p>"
    copyright = "Copyright (c) 2015 - 2021, Observatorio de Cohesión Social; todos los derechos reservados."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>COES</strong>
        <br>13/25 Diagonal Paraguay 257
        <br>Torre 26, Oficina 1504
        <br>Santiago-RM
        <br>Chile
        <br>
      </p>
      """

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contáctenos en ocs@coes.cl</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.test]
    enable = true
    title = "Sobre el OCS" 
    subtitle = "El **Observatorio de Cohesión Social (OCS)** es una iniciativa del **Centro de Estudios de Conflicto y Cohesión Social (COES)** que propone contribuir a la conceptualización y análisis empírico de la cohesión social en Chile, como también a su estudio en perspectiva comparada internacional. Los esfuerzos del observatorio han estado orientados en dos ámbitos de trabajo:  <br> <br> <b>1. Reportes</b> a través de los cuales se han revisado las experiencias internacionales en el estudio de la cohesión social, como también su conceptualización y métodos de medición <br><br> <b>2. Análisis</b> de datos sobre cohesión social, dentro de lo cual destaca una propuesta para la medición empírica en Chile y América Latina"

    
    
[params.features]
    enable = true
    cols= 2
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
 
[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Equipo"
    subtitle = ""

[params.see_more]
    enable = false
    icon = "fas fa-chart-line"
    title = "Indicadores Comparativos de Cohesión Social para América Latina"
    subtitle = ""
    link_url = "/app/"
    link_text = "Ir a visualizador"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = ""
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Noticias"
    subtitle = "En el siguiente apartado se pueden ver las noticias que han aparecido sobre el Observatorio de Cohesión Social"
